language: rust

sudo: false

script:
  - "cargo build --verbose"
  - "cargo test --verbose --features=$FEATURES"

env:
  - ""
  - "FEATURES=high_precision"

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

git:
  submodules: false
